### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Juancho1162** [SAP-samples/btp-cap-genai-rag#31]
The following documentation is empty:
![image006](https://github.com/user-attachments/assets/59e02d35-7da6-4fb2-a511-416d257882e6)
![image005](https://github.com/user-attachments/assets/94c2a550-e747-479d-9942-1879fe99e645)
![image004](https://github.com/user-attachments/assets/2b290e3f-b149-480a-af07-a2c1597cb77c)
![image003](https://github.com/user-attachments/assets/593c6c63-a0ed-4845-8f9d-e1723c1269b7)
![image002](https://github.com/user-attachments/assets/fd05264b-5057-4895-b3e5-99425c81a41b)
![image001](https://github.com/user-attachments/assets/cf8a9027-5fed-405b-aa30-5c661069453a)

**Comment by kay-schmitteckert** [comment]
Hi @Juancho1162,

the documentation and the Discovery Center mission were updated and unfortunately you have an outdated state of the mission which doesn't fit to the documentation in the repository.

Please restart your mission to have an up to date documentation which doesn't have a dedication section for setting up generative AI hub since it's part of the Cloud Foundry build (MTA).

Best
Kay
