### ISSUE TITLE
Frontend not reachable

### ISSUE THREAD

**Issue by gekko68** [SAP-samples/btp-cap-genai-rag#34]
Hey, after deployment the UI is not reachable ... 503 Service Temporarily Unavailable

However the endpoint for injecting mails works fine.

any idea what to check ?

**Comment by kay-schmitteckert** [comment]
Hi @gekko68,

- Was the deployment successful? Do you have the logs?
- Is the UAA bound to the App Router?

Best
Kay

**Comment by gekko68** [comment]
Hi  successful deployed :

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/7daa8105-8794-4144-a5ea-b9b2a7b5d3ea">


and the UAA :
 
<img width="903" alt="image" src="https://github.com/user-attachments/assets/205b80e6-e4c1-4910-b376-0069f11e61fa">

Logs look okay as well 

But still even after build/redeployment same issue ..

Thx for your support , Mike

**Comment by kay-schmitteckert** [comment]
Hi @gekko68,

during the latest refactoring, it seems that we adjusted the path of the url "/ui" but not the app.id from the SAPUI5 application. That means that the approuter points to /ui but the actual application can only be found with the defined app.id of the SAPUI5 application in the html5-repo.

Can you test pointing to /aiui (/aiui/index-cdn.html) instead of /ui?

We are looking into this again and after testing, provide an update on the respective parts of the SAPUI5 manifest.

Thanks for pointing this out!

Best

**Comment by gekko68** [comment]
> aiui

Hey Kay,
made the change and it is working ... 

Cheers and thx a lot...
